### ISSUE TITLE
Wish ESP32_ScreenShotReceiver can run on TFT3.5inch

### ISSUE THREAD

**Issue by BlynkGO** [lovyan03/ESP32_ScreenShotReceiver#4]
![PHOTO_20200720_164753](https://user-images.githubusercontent.com/65327357/87924382-09bebb80-caa9-11ea-8565-5e63e8d49139.jpg)

ESP32_ScreenShotReceiver is the great project.
I wish to use on TFT3.5 inch too, but can't display correctly.
How to fix the issue?

Thank you.

**Comment by lovyan03** [comment]
https://github.com/lovyan03/ESP32_ScreenShotReceiver/issues/3

**Comment by lovyan03** [comment]
I've just updated the master branch. It should now work with ILI9488.

**Comment by BlynkGO** [comment]
@lovyan03 
It's work now for 480x320 ILI9488.
Thanks a lot.
