### ISSUE TITLE
Cross-platform operation?

### ISSUE THREAD

**Issue by modi12jin** [lovyan03/ESP32_ScreenShotReceiver#8]
Are there any cross-platform ideas?  I want to run it on Linux or Mac.

**Comment by modi12jin** [comment]
I found a warehouse on github that uses VNC to implement cross-platform.  https://github.com/Links2004/arduinoVNC

**Comment by lovyan03** [comment]
@modi12jin 
Please read #7 Issue.

I don't plan to make it, but it looks like one of Arnaud's projects was created in Processing.
https://github.com/neofuturism/cheApR
