### ISSUE TITLE
How to get in touch with you?

### ISSUE THREAD

**Issue by neofuturism** [lovyan03/ESP32_ScreenShotReceiver#9]
Hello Lovyan03, it's been a few months since I've bothered you, 
but I'm still working on the same project as before and was able to make it a lot better,
I want to know if you would like to have an early prototype of my AR goggles,
here's the [PCB (i.g. link)](https://www.instagram.com/p/CQf11mJrjL7/?utm_source=ig_web_copy_link), and here's what the goggles [video 1](https://www.instagram.com/p/CQqv-BqDc9u/) [[video 2]](https://www.instagram.com/p/CQlF242LBk6/?utm_source=ig_web_copy_link) look like. 
I will open-source once I'm sure they won't catch fire. :)
Let me know if you're interested. I will gladly make you a full kit.
Cheers, 

Arnaud

**Comment by lovyan03** [comment]
@neofuturism 
Hello. It's been a while.

I am glad to see that your project is evolving.

I just followed you on Instagram, so you can use that to get in touch with me.
(But I don't use Instagram much, so I might be late to notice the notification.
